### ISSUE TITLE
No exported member to check weather clone is applied or not (on scroll).

### ISSUE THREAD

**Issue by hparth** [jonaszuberbuehler/ion-affix#10]
Is there any way/member using which I come to know that ion-affix clone event is applied or not?

Like When ion-affix header is in sticky mode, it should return some Boolean value and after release of that it should return reverse Boolean value.

**Comment by jonaszuberbuehler** [comment]
@hparth You mean sth that is pushed to the owning component? No, that's currently not possible (but kinda interesting for certain use cases I think). If pull is ok in your case you can access the IonAffix via `@ViewChild('header', {read: IonAffix}) ionAffix` and check for the `clone` member on it (meaning it's sticky).

**Comment by jonaszuberbuehler** [comment]
@hparth Would an event be helpful or does `clone` do the trick for you?

**Comment by jonaszuberbuehler** [comment]
@hparth could you post back what solution you’d like to see?

**Comment by jonaszuberbuehler** [comment]
@hparth Included in version 1.0.9.

**Comment by hparth** [comment]
Thanks. It worked.
