### ISSUE TITLE
Need Example for proper implementation in IONIC 3

### ISSUE THREAD

**Issue by Neotrixsx** [jonaszuberbuehler/ion-affix#11]
I try lot of time to implement ion-affix plugin in my IONIC 3 App I follow all given instruction in document . But every time I get same error. Please help me.

Error:

```
ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'content' since it isn't a known property of 'ion-item'.
```

**Comment by jonaszuberbuehler** [comment]
Could you post your code, especially the template where you wanna use the
ion-affix? Thx

**Comment by Neotrixsx** [comment]
I was using given example form document,
    `<ion-content padding #content>
   <ion-list>
       <ion-list-header ion-affix [content]="content" (click)="test()">Group 1</ion-list-header>
       <ion-item *ngFor="let item of items">{{item}}</ion-item>
   </ion-list>
   <ion-list>
       <ion-list-header ion-affix [content]="content">Group 2</ion-list-header>
       <ion-item *ngFor="let item of items">{{item}}</ion-item>
   </ion-list>
</ion-content>`

**Comment by hparth** [comment]
Make sure you have imported ionAffixModule in your module.ts file.

**Comment by jonaszuberbuehler** [comment]
As @hparth mentioned please make sure you import the module as described. The error message means that the content property coming from ion-affix is not known.

**Comment by Neotrixsx** [comment]
Thanks @hparth and @jonaszuberbuehler  for your reply. After reinstall **ion-affix**  its work fine. My application doesn't import **ion-affix** properly  because of that it's not working.

**Comment by jonaszuberbuehler** [comment]
Ok, glad it works now. Closing issue.
