### ISSUE TITLE
cordova build error

### ISSUE THREAD

**Issue by vnabet** [jonaszuberbuehler/ion-affix#15]
Version 1.1.1
on Ionic 3
When I build my app I have this error "ERROR in ./node_modules/rxjs/observable/BoundCallbackObservable.js
Module build failed: TypeError: Cannot read property 'type' of undefined"

**Comment by jonaszuberbuehler** [comment]
@vnabet Thx for the issue. Can you give me some more information on when the error happens? What platform you're building for? Does it only happen if this module is being included?

EDIT: Maybe the demo app source is of any help: https://github.com/jonaszuberbuehler/ion-affix-demo

**Comment by vnabet** [comment]
I build from a mac.
And yes, when I remove this module there is no error.

**Comment by jonaszuberbuehler** [comment]
Can you please post `ionic info`?

**Comment by vnabet** [comment]
cli packages: (/Users/eleve/.nvm/versions/node/v6.10.3/lib/node_modules)

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.9.2 
    Node       : v6.10.3
    npm        : 3.10.10 
    OS         : macOS Sierra
    Xcode      : Xcode 9.1 Build version 9B55 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : pro

**Comment by jonaszuberbuehler** [comment]
Downgraded my env to node 6.10.3 and adapted my sample project to match yours. Deleted `node-modules`, did a `npm install` and both `ionic cordova build ios` and `ionic cordova build android` pass. I can't reproduce your error. The only difference is the macOS version which is unlikely to cause the error.

Is your project public available or can you push a minimal example to your github?

**Comment by vnabet** [comment]
Hum... **I removed and re-added platforms**. And now it's ok ! weird...
Sorry for the inconvenience

**Comment by jonaszuberbuehler** [comment]
Strange indeed... hope you like the module anyway!
