### ISSUE TITLE
Cannot find module "rxjs/operators"

### ISSUE THREAD

**Issue by jorgemejia** [jonaszuberbuehler/ion-affix#20]
After install this directive, and make ionic serve. 

the page serve shows Cannot find module "rxjs/operators"

this is my enviroment info:

    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : ios 4.4.0
    Ionic Framework    : ionic-angular 3.7.0

System:

    ios-deploy : 1.9.2 
    ios-sim    : 5.0.8 
    Node       : v7.2.1
    npm        : 3.10.10 
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b 

Environment Variables:

    ANDROID_HOME : not set

Misc:

    backend : legacy

**Comment by jorgemejia** [comment]
I've update rxjs to version 5.5.6 :) and this issue disappear

**Comment by jonaszuberbuehler** [comment]
Thx. I need to pay more attention to required peer dependencies, which is not always easy to find out.
