### ISSUE TITLE
Ionic 3 - can't find module "rxjs/operators"

### ISSUE THREAD

**Issue by alexshak** [jonaszuberbuehler/ion-affix#24]
Getting the above error when running `ionic serve`. I have checked node_modules/rjxs/operators and the module is there, I'm also calling specific operators for other parts of the project. 

I have deleted node_modules and reinstalled for good measure. Any ideas?

**Comment by jonaszuberbuehler** [comment]
Did you check whether you're using rxjs 5.5.x in your package.json and you're imports are correct (like `import { map, pairwise, tap } from 'rxjs/operators';`)?

**Comment by alexshak** [comment]
Thanks Jonaz, 

I had thought the rjxs Ionic had installed was doing the job but I needed to update it and add it manually.
