### ISSUE TITLE
Improve segment support

### ISSUE THREAD

**Issue by wbhob** [jonaszuberbuehler/ion-affix#3]
I have an `ion-segment` used to switch between templates in my page, but the first header item is stuck to the navbar when switching tabs, instead of vanishing. 

Can you please make ion-affixed items check their state?

<img width="360" alt="screen shot 2017-07-02 at 11 10 15 pm" src="https://user-images.githubusercontent.com/4442130/27776800-a105b03a-5f7b-11e7-9cb2-0bfd4dd0d30a.png">

**Comment by jonaszuberbuehler** [comment]
Good point @wbhob. I use it in ion-tabs where this is no issue. Will have a look ASAP.

**Comment by jonaszuberbuehler** [comment]
@wbhob Can you try version 1.0.3? Should be on npm. Short feedback appreciated.

**Comment by jonaszuberbuehler** [comment]
Closing since no reply

**Comment by wbhob** [comment]
Yeah sorry, haven't gotten a chance to test yet, I've been super busy with other projects. I'll hopefully get to it today or tomorrow

**Comment by jonaszuberbuehler** [comment]
No worries. Annoying habit from work to close issues if no reply is given within one day :).
