### ISSUE TITLE
 has no exported member 'Renderer2'.

### ISSUE THREAD

**Issue by pablohadler** [jonaszuberbuehler/ion-affix#9]
node_modules/ion-affix/dist/directives/ion-affix.d.ts

 import { AfterViewInit, ElementRef, OnDestroy, Renderer2 } from '@angular/core';

**Comment by jonaszuberbuehler** [comment]
Can you give me some information about what Ionic version you're using (`ionic info`)?

**Comment by pablohadler** [comment]
Ionic Framework: 2.1.0
Ionic Native: 2.4.1
Ionic App Scripts: 1.1.3
Angular Core: 2.2.1
Angular Compiler CLI: 2.2.1
Node: 6.7.0
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Comment by jonaszuberbuehler** [comment]
Any chance you can upgrade Ionic to >3.0.0? Renderer2 was introduced with
Angular4 (replacing Renderer) which Ionic depends on. If that’s not
possible I could push a fix working for older Ionic versions.

**Comment by jonaszuberbuehler** [comment]
@pablohadler Can I help you to get your problem fixed?

**Comment by jonaszuberbuehler** [comment]
Closing due inactivity
